name: bosbase
description: Multi-platform Dart SDK for Bosbase, an open source realtime backend in 1 file.
repository: https://github.com/bosbase/dart-sdk

version: 0.25.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  http: ^1.3.0
  json_annotation: ^4.9.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.0.0
  lints: ^5.0.0
  test: ^1.16.0
